#! /bin/sh
# /etc/init.d/selena

### BEGIN INIT INFO
# Provides:          selena
# Required-Start:    $all
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start Selena client
# Description:       Experimental work.
### END INIT INFO

# The following part always gets executed.
#echo "This part always gets executed"

# The following part carries out specific functions depending on arguments.
case "$1" in
  start)
    echo "Starting selena client"
    /usr/bin/selena_agent.py start
    ;;
  stop)
    echo "Stopping selena client"
    /usr/bin/selena_agent.py stop
    ;;
  restart)
    echo "Restarting selena client"
    /usr/bin/selena_agent.py restart
    ;;
  status)
    echo "Getting selena status"
    /usr/bin/selena_agent.py status
    ;;  
  *)
    echo "Usage: /etc/init.d/selena {start|stop|restart/status}"
    exit 1
    ;;
esac

exit 0
