#! /bin/sh
# /etc/init.d/selena

### BEGIN INIT INFO
# Provides:          selena
# Required-Start:    $all
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start Selena client
# Description:       Experimental work.
### END INIT INFO

# The following part always gets executed.
echo "This part always gets executed"

# The following part carries out specific functions depending on arguments.
case "$1" in
  start)
    echo "Starting selena client"
    /root/bin/scripts/startSelenaClient.sh
    ;;
  stop)
    echo "Stopping selena client"
    /usr/bin/killall python
    echo "Selena client is dead"
    ;;
  *)
    echo "Usage: /etc/init.d/selena {start|stop}"
    exit 1
    ;;
esac

exit 0
